# Generated by Django 5.0.1 on 2024-01-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
